theme = "gruvbox"

[editor]
cursorline = true
auto-format = true
true-color = true
color-modes = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 2000

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"
